services:
    postgres: 
        image: postgres
        environment:
            - POSTGRES_PASSWORD=123456
            - POSTGRES_USER=postgres
        ports:
            - 5432:5432
        volumes:
            - pgdata:/var/lib/postgresql/data
    rabbitmq:
        image: rabbitmq:3-management-alpine
        ports:
            - 5672:5672
            - 15672:15672
    expense-svc:
        image: expense-svc:v1.0.0-development
        build:
            context: .
            dockerfile: src/ExpenseService/Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=http://+:80   
            - ConnectionStrings__DefaultConnection=Server=postgres:5432;Database=expenses;Username=postgres;Password=123456
        ports:
            - 4001:80
        depends_on:
            - postgres
    income-svc:
        image: income-svc:v1.0.0-development
        build:
            context: .
            dockerfile: src/IncomeService/Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=http://+:80   
            - ConnectionStrings__IncSvcConnection=Server=postgres:5432;Database=incomes;Username=postgres;Password=123456
        ports:
            - 4002:80
        depends_on:
            - postgres
    goal-svc:
        image: goal-svc:v1.0.0-development
        build:
            context: .
            dockerfile: src/GoalsService/Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=http://+:80   
            - ConnectionStrings__GoalSvcConnection=Server=postgres:5432;Database=goals;Username=postgres;Password=123456
        ports:
            - 4003:80
        depends_on:
            - postgres
    gateway-svc:
        image: gateway-svc:v1.0.0-development
        build:
            context: .
            dockerfile: src/GatewayService/Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Docker
            - ASPNETCORE_URLS=http://+:80   
        ports:
            - 6002:80
    heatmap-svc:
        image: heatmap-svc:v1.0.0-development
        build:
            context: .
            dockerfile: src/HeatmapService/Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=http://+:80   
            - ConnectionStrings__HeatmapConnection=Server=postgres:5432;Database=heatmaps;Username=postgres;Password=123456
        ports:
            - 4004:80
        depends_on:
            - postgres
volumes:
    pgdata:
